import { Container, Flex, Heading, Image, VStack } from "@chakra-ui/react"
import axios from "axios"
import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import React, { useEffect, useState } from "react"
import { Listing } from "types"

const Listings: NextPage = () => {
  const router = useRouter()
  const { id } = router.query
  const [listing, setListing] = useState<Listing | null>(null)
  if (listing) {
    console.log("listing:", listing.reviews)
  }

  useEffect(() => {
    axios.get<{ listing: Listing }>(`/api/listings/${id}`).then((r) => {
      setListing(r.data.listing)
    })
  }, [id])

  return (
    <Flex h="100vh" direction="column" w="100%">
      <Head>
        <title>See all listings in your area</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl" pt={4}>
        {listing && (
          <VStack spacing={4} align="left">
            <Heading size="lg">{listing.name}</Heading>
            <Image
              borderRadius="md"
              alt={listing.summary}
              src={listing.images.picture_url}
              w="60%"
              h="300px"
              objectFit="cover"
            />
            <Heading size="md">Reviews</Heading>
          </VStack>
        )}
      </Container>
    </Flex>
  )
}

export default Listings
